#!/usr/bin/env python3
"""
Step 4 validator/report generator for the v2.2 blinded pattern-annotation
remediation (Option A). Run after annotation reaches (or is checked against)
232/232.

Reads:
  - annotation_v2_2/blinded_records.jsonl  (the canonical 232-program frame)
  - data/manifests/pattern_annotations_v2_2.csv  (human decisions, latest
    row per program_id)

Writes:
  - data/manifests/PATTERN_ANNOTATION_AUDIT_V2_2.md

Does NOT touch pilot_manifest_v2_1.json, does NOT recompute class selection,
and does NOT build pilot_manifest_v2_2.json -- that is Step 5, performed
only after this script reports COMPLETE and the user explicitly proceeds.

Usage:
    .venv/bin/python scripts/validate_pattern_annotations_v2_2.py
"""
from __future__ import annotations

import csv
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RECORDS_FILE = REPO_ROOT / "annotation_v2_2" / "blinded_records.jsonl"
ANNOTATIONS_CSV = REPO_ROOT / "data" / "manifests" / "pattern_annotations_v2_2.csv"
OUT_MD = REPO_ROOT / "data" / "manifests" / "PATTERN_ANNOTATION_AUDIT_V2_2.md"

VOCAB = [
    "two_pointers", "sliding_window", "binary_search", "prefix_sums",
    "dynamic_programming", "greedy", "graph_traversal_dfs_bfs",
    "sorting_based", "hash_map_counting", "brute_force_implementation",
    "intervals", "simulation",
]
VALID_CONFIRMED = set(VOCAB) | {"outside_vocabulary"}


def load_records() -> list[dict]:
    records = []
    with open(RECORDS_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def load_latest_annotations() -> dict[str, dict]:
    latest: dict[str, dict] = {}
    if ANNOTATIONS_CSV.exists():
        with open(ANNOTATIONS_CSV, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                latest[row["program_id"]] = row
    return latest


def main() -> None:
    records = load_records()
    latest = load_latest_annotations()

    confirmed_rows = {}
    missing = []
    pending = []
    for r in records:
        row = latest.get(r["program_id"])
        if row is not None and row["pattern_label"] in VALID_CONFIRMED:
            confirmed_rows[r["program_id"]] = row
        elif row is not None and row["pattern_label"] in ("UNCERTAIN", "SKIP"):
            pending.append(r["program_id"])
        else:
            missing.append(r["program_id"])

    total = len(records)
    n_confirmed = len(confirmed_rows)
    complete = n_confirmed == total

    label_counts = Counter(row["pattern_label"] for row in confirmed_rows.values())
    confidence_counts = Counter(row["confidence"] for row in confirmed_rows.values() if row["pattern_label"] != "outside_vocabulary")
    outside_vocab_reasons = [
        (pid, row["annotation_note"])
        for pid, row in confirmed_rows.items()
        if row["pattern_label"] == "outside_vocabulary"
    ]

    lines: list[str] = []
    lines.append("# Pattern Annotation Audit — v2.2 (Blinded Human Re-Annotation)")
    lines.append("")
    lines.append(
        f"**Status: {'COMPLETE' if complete else 'IN PROGRESS'} "
        f"({n_confirmed}/{total} confirmed)**"
    )
    lines.append("")
    lines.append(
        "Generated by `scripts/validate_pattern_annotations_v2_2.py` at "
        f"{datetime.now(timezone.utc).isoformat()}."
    )
    lines.append("")
    lines.append(
        "Remediation of the pattern-label provenance violation documented in "
        "`data/PATTERN_LABEL_PROVENANCE_AUDIT.md` (Option A, user-authorized). "
        "This report covers the blinded human re-annotation of the "
        "task-independent frame F_v2.1 (232 programs) only. It does not "
        "modify `pilot_manifest_v2_1.json`, which remains frozen and unmodified "
        "as permanent audit history, and it does not perform class selection "
        "or sampling (Step 5)."
    )
    lines.append("")
    lines.append("## 1. Completeness")
    lines.append("")
    lines.append(f"- Frame size: **{total}**")
    lines.append(f"- Confirmed (valid vocabulary label or `outside_vocabulary`): **{n_confirmed}**")
    lines.append(f"- Pending (marked uncertain or skipped, not yet resolved): **{len(pending)}**")
    lines.append(f"- Never touched: **{len(missing)}**")
    lines.append("")
    if not complete:
        lines.append(
            "**This annotation pass is INCOMPLETE. Step 5 (sampling rebuild) "
            "must not proceed until this section reports 232/232 confirmed.**"
        )
        lines.append("")
        if pending:
            lines.append(f"Pending program_ids ({len(pending)}): " + ", ".join(sorted(pending)))
            lines.append("")
        if missing:
            lines.append(f"Never-touched program_ids ({len(missing)}): " + ", ".join(sorted(missing)))
            lines.append("")
        lines.append(
            "Resume annotation with `.venv/bin/python "
            "scripts/annotate_patterns_v2_2.py` (continues automatically) "
            "or `--revisit` (pending only)."
        )
    else:
        lines.append("All 232 programs have a human-confirmed label. Step 5 may proceed.")
    lines.append("")

    lines.append("## 2. Class distribution among confirmed labels")
    lines.append("")
    lines.append("| Pattern class | Count | Threshold (≥ 7) |")
    lines.append("|---|---:|:---:|")
    for slug in VOCAB:
        count = label_counts.get(slug, 0)
        lines.append(f"| `{slug}` | {count} | {'Yes' if count >= 7 else 'No'} |")
    lines.append(f"| `outside_vocabulary` | {label_counts.get('outside_vocabulary', 0)} | N/A |")
    lines.append("")

    if complete:
        eligible = [(slug, label_counts.get(slug, 0)) for slug in VOCAB if label_counts.get(slug, 0) >= 7]
        eligible.sort(key=lambda t: (-t[1], VOCAB.index(t[0])))
        lines.append("### Class ranking under `SAMPLING_PROTOCOL.md` §6 (descending count, vocabulary-order tie-break)")
        lines.append("")
        if eligible:
            lines.append("| Rank | Class | Count |")
            lines.append("|---:|---|---:|")
            for i, (slug, count) in enumerate(eligible, start=1):
                lines.append(f"| {i} | `{slug}` | {count} |")
        else:
            lines.append("No class reaches the ≥ 7-program threshold.")
        lines.append("")
        lines.append(
            "This ranking is computed here for transparency only. Step 5's "
            "packaging script recomputes it independently against the same "
            "confirmed annotation CSV before drawing the final sample."
        )
        lines.append("")

    lines.append("## 3. Confidence distribution (excluding outside_vocabulary)")
    lines.append("")
    for level in ("high", "medium", "low"):
        lines.append(f"- {level}: {confidence_counts.get(level, 0)}")
    lines.append("")

    lines.append("## 4. `outside_vocabulary` programs and stated reasons")
    lines.append("")
    if outside_vocab_reasons:
        lines.append("| program_id | reason |")
        lines.append("|---|---|")
        for pid, note in sorted(outside_vocab_reasons):
            lines.append(f"| {pid} | {note or '(no reason given)'} |")
    else:
        lines.append("None recorded yet.")
    lines.append("")

    lines.append("## 5. Comparison against the disputed automated (\"AST rule\") labels")
    lines.append("")
    lines.append(
        "Deliberately not computed by this script: the blinded annotation "
        "workspace never loaded the old `pattern_label`/`pattern_source` "
        "values (see `annotation_v2_2/frame_manifest.json`'s exclusion list), "
        "so no per-program agreement/disagreement rate against the disputed "
        "labels can be produced from this data alone. A separate, explicitly "
        "requested comparison script would need to join this CSV against "
        "`pilot_manifest_v2.json`/`pilot_manifest_v2_1.json` after the fact, "
        "outside the annotation session itself, to avoid any risk of the "
        "old labels influencing an in-progress annotation."
    )
    lines.append("")

    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_MD}")
    print(f"Status: {'COMPLETE' if complete else 'IN PROGRESS'} ({n_confirmed}/{total})")


if __name__ == "__main__":
    main()
